-- AUTO-GENERATED by matugen — do not edit by hand, edit the template instead
-- Template: ~/.config/matugen/templates/hyprland-colors.lua.template

local M = {}

M.primary   = "ffffff"
M.secondary = "c6c6c6"
M.surface   = "131313"
M.on_surface = "e2e2e2"

return M
