-- AUTO-GENERATED by matugen — do not edit by hand, edit the template instead
-- Template: ~/.config/matugen/templates/hyprland-colors.lua.template

local M = {}

M.primary   = "b8c3ff"
M.secondary = "c3c5dd"
M.surface   = "121318"
M.on_surface = "e3e1e9"

return M
