-- AUTO-GENERATED by matugen — do not edit by hand, edit the template instead
-- Template: ~/.config/matugen/templates/hyprland-colors.lua.template

local M = {}

M.primary   = "ffb2bd"
M.secondary = "e5bdc1"
M.surface   = "191112"
M.on_surface = "f0dee0"

return M
