theme = "tokyonight"

[editor]
shell = ["fish", "-c"]
idle-timeout = 50
completion-timeout = 50
completion-trigger-len = 1

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "│"
skip-levels = 0
